# Site Settings
title: Hi there, I'm Rafaell
email: sonny.webdsg@gmail
description: >
  Web development, front end stuff, tutorials for beginners and more by Rafaell Lycan
baseurl: "/"
url: "http://rafaell-lycan.com" # the base hostname & protocol for your site
author: Rafaell Lycan
twitter: RafaellLycan
github: rafaell-lycan

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments # Use pygments to highlight code blocks
kramdown:
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

gems: ['jekyll-paginate']
paginate: 10

destination: ./_publish

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Category Settings
category_title_prefix: ''
category_dir: /

# Others
future: false
show_drafts: false

# exclude my node related stuff
exclude: ['package.json', 'node_modules', 'src', '.gitignore', 'gulpfile.js', 'README.md']
